import React from 'react'
import TextContainer from './TextContainer'

const MEASURE = '40rem'

const TextColumn = ({ children, footnotes }) => (
  <div
    css={`
      display: grid;
      position: relative;
      padding: ${({ theme }) => theme.sizes.s2} 0;

      grid-template-columns: ${({ theme }) =>
        `${theme.sizes.s2} 1fr ${theme.sizes.s2}`};

      @media (min-width: ${780 / 16}em) {
        grid-template-columns: ${({ theme }) =>
          `minMax(${theme.sizes.s2} 1fr) ${MEASURE} minMax(${theme.sizes.s2}, 1fr)`};
      }

      @media (min-width: ${960 / 16}em) {
        grid-template-columns: ${({ theme }) => `1fr ${MEASURE} 2fr`};
      }

      // The CSS classes selected below are auto-generated by Gatsby,
      // hence a lack of more specific styling via styled-components

      // Stop code blocks, images and footnotes from overflowing
      .gatsby-highlight,
      .gatsby-resp-image-link,
      .no-overflow,
      .footnotes {
        overflow: scroll;
        // Set max-width to viewport width, minus the width of the TextColumn
        // spacer divs specified above in grid-template-columns
        max-width: calc(
          100vw -
            ${({ theme }) => `${theme.sizes.s2} - ${theme.sizes.s2}`}
        );
      }
    `}
  >
    <div />
    <TextContainer>{children}</TextContainer>
    <div />
  </div>
)

export default TextColumn
